version: "3.8"
services: 
  api:
    build: ./api
    container_name: api_c
    ports: 
      - '4000:4000'
    volumes:
      - ./api:/app
      - /c/Users/HP/Desktop/Docker/docker-project/api/node_modules:/app/node_modules