version: "3.8"
services: 
  api:
    build: ./api
    container_name: api_c
    ports: 
      - '4000:4000'
    volumes:
      - ./api:/app
      - /c/Users/HP/Desktop/Docker/project-1337/api/node_modules:/app/node_modules
      
  tic-tac-toe:
    build: ./tic-tac-toe
    container_name: react-container
    ports: 
      - '3000:3000'
      
    volumes:
      - ./api:/app
      - /c/Users/HP/Desktop/Docker/project-1337/api/node_modules:/app/node_modules
      